# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-30 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeluguactorsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField(max_length=100)),
                ('feedback', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=50)),
                ('salary', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
